name: Slack Message Test

on:
  schedule:
    # 평일 KST 16:30
    - cron: 30 7 * * 1-5
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0

      - name: slack-send
        uses: slackapi/slack-github-action@v1.18.0
        with:
          payload: |
            {
              "text": "Test Message: scheduled run"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
